// Flutter asset parity map for the React Native app.
// PNG/JPG files are exported as RN static resources via require(...).
// SVG icons are exported as path strings until svg transformer import support is added.

export const FLUTTER_ALL_ASSET_PATHS = [
    'assets/Icons/add.svg',
    'assets/Icons/Arrow.svg',
    'assets/Icons/backward.svg',
    'assets/Icons/bell.svg',
    'assets/Icons/Cadiologist.svg',
    'assets/Icons/Calender.svg',
    'assets/Icons/Cards.svg',
    'assets/Icons/Chat.svg',
    'assets/Icons/Chevron more.svg',
    'assets/Icons/Degree.svg',
    'assets/Icons/Dentists.svg',
    'assets/Icons/Doctor Male.svg',
    'assets/Icons/doctor-1.svg',
    'assets/Icons/doctor.svg',
    'assets/Icons/Download.svg',
    'assets/Icons/Edit.svg',
    'assets/Icons/False.svg',
    'assets/Icons/Favorite_sml.svg',
    'assets/Icons/filter.svg',
    'assets/Icons/forward.svg',
    'assets/Icons/Frame 2608268.svg',
    'assets/Icons/Gastroenterologists.svg',
    'assets/Icons/Hepatologists.svg',
    'assets/Icons/Home.svg',
    'assets/Icons/Hospital.svg',
    'assets/Icons/IconsCall_Hung.svg',
    'assets/Icons/Injection.svg',
    'assets/Icons/Kebab.svg',
    'assets/Icons/lock.svg',
    'assets/Icons/log-out.svg',
    'assets/Icons/Loud speaker.svg',
    'assets/Icons/Medical Prescription.svg',
    'assets/Icons/Medical.svg',
    'assets/Icons/medicine.svg',
    'assets/Icons/Mineral Water.svg',
    'assets/Icons/More.svg',
    'assets/Icons/Nephrologists.svg',
    'assets/Icons/Neurologists.svg',
    'assets/Icons/notifications.svg',
    'assets/Icons/Paper Plane Tilt.svg',
    'assets/Icons/patient_icon.png',
    'assets/Icons/Psychiatrists.svg',
    'assets/Icons/Pulmonologists.svg',
    'assets/Icons/Reports.svg',
    'assets/Icons/Room.svg',
    'assets/Icons/Run.svg',
    'assets/Icons/Search.svg',
    'assets/Icons/Seccessful.svg',
    'assets/Icons/Secured.svg',
    'assets/Icons/Send.svg',
    'assets/Icons/session complete.svg',
    'assets/Icons/show more.svg',
    'assets/Icons/Sign out.svg',
    'assets/Icons/Sleep.svg',
    'assets/Icons/Star.svg',
    'assets/Icons/stethoscope.svg',
    'assets/Icons/Term And Policy.svg',
    'assets/Icons/Theme.svg',
    'assets/Icons/Time.svg',
    'assets/Icons/Upload.svg',
    'assets/Icons/user.svg',
    'assets/Icons/Verified.svg',
    'assets/Icons/Video call.svg',
    'assets/Icons/Voice Call.svg',
    'assets/Icons/Voice.svg',
    'assets/Images/2 Doctors.png',
    'assets/Images/Blog image.png',
    'assets/Images/Thumbnail.png',
] as const;

export const FLUTTER_RASTER_ASSETS = {
    iconsPatientIconPng: require('../../assets/Icons/patient_icon.png'),
    imagesN2DoctorsPng: require('../../assets/Images/2 Doctors.png'),
    imagesBlogImagePng: require('../../assets/Images/Blog image.png'),
    imagesThumbnailPng: require('../../assets/Images/Thumbnail.png'),
} as const;

export const FLUTTER_IMAGE_ASSETS = {
    'assets/Images/2 Doctors.png': require('../../assets/Images/2 Doctors.png'),
    'assets/Images/Blog image.png': require('../../assets/Images/Blog image.png'),
    'assets/Images/Thumbnail.png': require('../../assets/Images/Thumbnail.png'),
} as const;

export const FLUTTER_ICON_SVG_PATHS = {
    'assets/Icons/add.svg': 'assets/Icons/add.svg',
    'assets/Icons/Arrow.svg': 'assets/Icons/Arrow.svg',
    'assets/Icons/backward.svg': 'assets/Icons/backward.svg',
    'assets/Icons/bell.svg': 'assets/Icons/bell.svg',
    'assets/Icons/Cadiologist.svg': 'assets/Icons/Cadiologist.svg',
    'assets/Icons/Calender.svg': 'assets/Icons/Calender.svg',
    'assets/Icons/Cards.svg': 'assets/Icons/Cards.svg',
    'assets/Icons/Chat.svg': 'assets/Icons/Chat.svg',
    'assets/Icons/Chevron more.svg': 'assets/Icons/Chevron more.svg',
    'assets/Icons/Degree.svg': 'assets/Icons/Degree.svg',
    'assets/Icons/Dentists.svg': 'assets/Icons/Dentists.svg',
    'assets/Icons/Doctor Male.svg': 'assets/Icons/Doctor Male.svg',
    'assets/Icons/doctor-1.svg': 'assets/Icons/doctor-1.svg',
    'assets/Icons/doctor.svg': 'assets/Icons/doctor.svg',
    'assets/Icons/Download.svg': 'assets/Icons/Download.svg',
    'assets/Icons/Edit.svg': 'assets/Icons/Edit.svg',
    'assets/Icons/False.svg': 'assets/Icons/False.svg',
    'assets/Icons/Favorite_sml.svg': 'assets/Icons/Favorite_sml.svg',
    'assets/Icons/filter.svg': 'assets/Icons/filter.svg',
    'assets/Icons/forward.svg': 'assets/Icons/forward.svg',
    'assets/Icons/Frame 2608268.svg': 'assets/Icons/Frame 2608268.svg',
    'assets/Icons/Gastroenterologists.svg': 'assets/Icons/Gastroenterologists.svg',
    'assets/Icons/Hepatologists.svg': 'assets/Icons/Hepatologists.svg',
    'assets/Icons/Home.svg': 'assets/Icons/Home.svg',
    'assets/Icons/Hospital.svg': 'assets/Icons/Hospital.svg',
    'assets/Icons/IconsCall_Hung.svg': 'assets/Icons/IconsCall_Hung.svg',
    'assets/Icons/Injection.svg': 'assets/Icons/Injection.svg',
    'assets/Icons/Kebab.svg': 'assets/Icons/Kebab.svg',
    'assets/Icons/lock.svg': 'assets/Icons/lock.svg',
    'assets/Icons/log-out.svg': 'assets/Icons/log-out.svg',
    'assets/Icons/Loud speaker.svg': 'assets/Icons/Loud speaker.svg',
    'assets/Icons/Medical Prescription.svg': 'assets/Icons/Medical Prescription.svg',
    'assets/Icons/Medical.svg': 'assets/Icons/Medical.svg',
    'assets/Icons/medicine.svg': 'assets/Icons/medicine.svg',
    'assets/Icons/Mineral Water.svg': 'assets/Icons/Mineral Water.svg',
    'assets/Icons/More.svg': 'assets/Icons/More.svg',
    'assets/Icons/Nephrologists.svg': 'assets/Icons/Nephrologists.svg',
    'assets/Icons/Neurologists.svg': 'assets/Icons/Neurologists.svg',
    'assets/Icons/notifications.svg': 'assets/Icons/notifications.svg',
    'assets/Icons/Paper Plane Tilt.svg': 'assets/Icons/Paper Plane Tilt.svg',
    'assets/Icons/Psychiatrists.svg': 'assets/Icons/Psychiatrists.svg',
    'assets/Icons/Pulmonologists.svg': 'assets/Icons/Pulmonologists.svg',
    'assets/Icons/Reports.svg': 'assets/Icons/Reports.svg',
    'assets/Icons/Room.svg': 'assets/Icons/Room.svg',
    'assets/Icons/Run.svg': 'assets/Icons/Run.svg',
    'assets/Icons/Search.svg': 'assets/Icons/Search.svg',
    'assets/Icons/Seccessful.svg': 'assets/Icons/Seccessful.svg',
    'assets/Icons/Secured.svg': 'assets/Icons/Secured.svg',
    'assets/Icons/Send.svg': 'assets/Icons/Send.svg',
    'assets/Icons/session complete.svg': 'assets/Icons/session complete.svg',
    'assets/Icons/show more.svg': 'assets/Icons/show more.svg',
    'assets/Icons/Sign out.svg': 'assets/Icons/Sign out.svg',
    'assets/Icons/Sleep.svg': 'assets/Icons/Sleep.svg',
    'assets/Icons/Star.svg': 'assets/Icons/Star.svg',
    'assets/Icons/stethoscope.svg': 'assets/Icons/stethoscope.svg',
    'assets/Icons/Term And Policy.svg': 'assets/Icons/Term And Policy.svg',
    'assets/Icons/Theme.svg': 'assets/Icons/Theme.svg',
    'assets/Icons/Time.svg': 'assets/Icons/Time.svg',
    'assets/Icons/Upload.svg': 'assets/Icons/Upload.svg',
    'assets/Icons/user.svg': 'assets/Icons/user.svg',
    'assets/Icons/Verified.svg': 'assets/Icons/Verified.svg',
    'assets/Icons/Video call.svg': 'assets/Icons/Video call.svg',
    'assets/Icons/Voice Call.svg': 'assets/Icons/Voice Call.svg',
    'assets/Icons/Voice.svg': 'assets/Icons/Voice.svg',
} as const;

export const FLUTTER_PLACEHOLDER_IMAGES = {
    patientIcon: FLUTTER_RASTER_ASSETS.iconsPatientIconPng,
    twoDoctors: FLUTTER_RASTER_ASSETS.imagesN2DoctorsPng,
    blogImage: FLUTTER_RASTER_ASSETS.imagesBlogImagePng,
    thumbnail: FLUTTER_RASTER_ASSETS.imagesThumbnailPng,
} as const;

export type FlutterAssetPath = (typeof FLUTTER_ALL_ASSET_PATHS)[number];
